test

diff --git a/.github/workflows/bikes.yml b/.github/workflows/bikes.yml
--- a/.github/workflows/bikes.yml
+++ b/.github/workflows/bikes.yml
@@ -72,7 +72,7 @@ jobs:
       run: |
         clientversion=$(echo $(helm version --client --short) | sed -n 's/.*Client: \(.*\)+.*/\1/p')
         serverversion=$(echo $(helm version --server --short) | sed -n 's/.*Server: \(.*\)+.*/\1/p')
-        [ -z "$serverversion" ] && echo echo "Error!" 1>&2
+        [ -z "$serverversion" ] && echo "Error!" 1>&2
         exit 64        
         if [[ "$clientversion" != "$serverversion" ]]; then   
           echo "Versions are equal"
